### ISSUE TITLE
Last xkcd comic.

### ISSUE THREAD

**Issue by daraujo3** [NightmareX91/HoloBot#1]
When the command -xkcd 1634 is prompted to the bot, it returns the "There are only 1634 xkcd comics!~" message where it should return the comic, since 1634 does exist

``` javascript
...
if (isnum) {
  if ([suffix] < xkcdInfo.num) {
    request('http://xkcd.com/' + suffix + '/info.0.json', function (error, response, body) {
...
```

**Comment by meanwhile0** [comment]
Should be fixed now. https://github.com/NightmareX91/HoloBot/commit/4274ea19205e725b7e04506b2c6e26fe9cdc7bb4
